language: java
sudo: true
services:
  - postgresql
before_install:
  - chmod +x mvnw
jdk:
  - oraclejdk8
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - psql -c 'create database testx;' -U postgres
script: mvn clean test
