spring.data.rest.base-path: /api
spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgres
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.database.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/testx
spring.datasource.username: postgres
spring.datasource.password: x
server.port: 8080
security:
  oauth2:
    client:
      clientId: 185595875273263
      clientSecret: 418555ea60a3d234c01007139f5c4f06
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me